async function loadSiteData(){const r=await fetch('content/site.json');if(!r.ok)throw new Error('Failed');return r.json()}
const $=s=>document.querySelector(s);const setText=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v}
function media(src,fallback){return `<div class="card-media" data-fallback="${fallback}"><img src="${src}" alt="${fallback}" loading="lazy" onerror="this.parentElement.classList.add('broken')"></div>`}
function renderNav(nav,current){const el=$('#site-nav');if(!el)return;el.innerHTML=nav.map(i=>`<a href="${i.href}" class="${i.href===current?'active':''}">${i.text}</a>`).join('')}
function renderBusiness(cards){const el=$('#home-entries');if(!el)return;el.innerHTML=cards.map(i=>`<article class="biz-card">${media(i.image,i.name)}<div class="biz-body"><h3>${i.name}</h3><p>${i.intro}</p><div class="btn-row"><a class="btn btn-light" href="${i.link}">${i.button}</a></div></div></article>`).join('')}
function renderProjectCards(target,cards,images,prefix){const el=document.getElementById(target);if(!el)return;el.innerHTML=cards.map((p,idx)=>`<article class="biz-card">${media(images[idx]||'',`${prefix}项目图片`)}<div class="biz-body"><h3>${p.name}</h3><p>${p.desc}</p></div></article>`).join('')}
function renderList(id,list){const el=document.getElementById(id);if(el)el.innerHTML=list.map(i=>`<li>${i}</li>`).join('')}
function renderFlow(id,list){const el=document.getElementById(id);if(el)el.innerHTML=list.map((i,x)=>`${x?'<i>→</i>':''}<span>${i}</span>`).join('')}
function setupNavToggle(){const t=$('#nav-toggle'),n=$('#site-nav');if(t&&n)t.onclick=()=>n.classList.toggle('open')}
async function init(){const d=await loadSiteData();const page=document.body.dataset.page;renderNav(d.site.nav,`${page}.html`);setText('brand-name',d.site.name);setText('brand-title',d.site.title);setText('footer-text',d.site.footer);
if(page==='index'){setText('hero-title',d.home.heroTitle);setText('hero-text',d.home.heroText);$('#hero-cta').textContent=d.home.ctaText;$('#hero-image').src=d.images.hero;$('#hero-image').onerror=()=>$('#hero-image-wrap').classList.add('broken');renderBusiness(d.home.businessEntrances);$('#core-capabilities').innerHTML=d.home.coreCapabilities.map(i=>`<div>${i}</div>`).join('');$('#home-gallery').innerHTML=[d.images.mechanical,d.images.embedded,d.images.automation,d.images.hero].map((s,i)=>`<div class="${i===0?'lg':''}">${media(s,'项目化训练与设计服务')}</div>`).join('')}
if(page==='mechanical'){setText('page-title',d.mechanical.pageTitle);setText('page-subtitle',d.mechanical.pageSubtitle);renderList('learning-path',d.mechanical.learningPath);renderProjectCards('project-cards',d.mechanical.projects,d.images.mechanicalProjects,'机械');setText('primary-btn',d.mechanical.primaryButton);setText('secondary-btn',d.mechanical.secondaryButton);$('#secondary-btn').href=d.links.mechanicalFormUrl}
if(page==='embedded'){setText('page-title',d.embedded.pageTitle);setText('page-subtitle',d.embedded.pageSubtitle);renderList('learning-directions',d.embedded.learningDirections);renderProjectCards('project-cards',d.embedded.projects,d.images.embeddedProjects,'嵌入式');setText('primary-btn',d.embedded.primaryButton);setText('secondary-btn',d.embedded.secondaryButton);$('#secondary-btn').href=d.links.embeddedFormUrl}
if(page==='automation'){setText('page-title',d.automation.pageTitle);setText('page-subtitle',d.automation.pageSubtitle);renderList('service-capabilities',d.automation.serviceCapabilities);renderList('delivery-list',d.automation.delivery);renderFlow('cooperation-flow',d.automation.flow);setText('primary-btn',d.automation.primaryButton);setText('secondary-btn',d.automation.secondaryButton);$('#secondary-btn').href=d.links.automationFormUrl}
if(page==='about'){setText('page-title',d.about.pageTitle);setText('brand-a-name',d.about.brandA.name);setText('brand-a-intro',d.about.brandA.intro);setText('brand-b-name',d.about.brandB.name);setText('brand-b-intro',d.about.brandB.intro)}
if(page==='contact'){setText('page-title',d.contact.pageTitle);setText('page-subtitle',d.contact.pageSubtitle);$('#contact-cards').innerHTML=d.contact.cards.map(c=>`<article class="panel"><h3>${c.title}</h3><p>${c.intro}</p><div class="btn-row"><a class="btn btn-primary" href="${d.links.contactPage}">${c.primaryButton}</a><a class="btn btn-accent" href="${d.links[c.formUrlKey]||'#'}">${c.secondaryButton}</a></div></article>`).join('')}
setupNavToggle()}
init().catch(console.error)
